### ISSUE TITLE
The 'Pitoco Extension' extension is not available in Visual Studio Code for Mac Silicon.

### ISSUE THREAD

**Issue by jungwookim** [pfeodrippe/pitoco#6]
Hi,

I would try to use it but VScode says `The 'Pitoco Extension' extension is not available in Visual Studio Code for Mac Silicon.`.

Could you have any workaround or plans to resolve it?

**Comment by pfeodrippe** [comment]
Hi @jungwookim, I published a version only for the web, but I can check how to publish the desktop version tonight. The code should be the same.

**Comment by pfeodrippe** [comment]
@jungwookim Beginning with the version `0.0.28` of  https://marketplace.visualstudio.com/items?itemName=feodrippe.pitoco-extension&ssr=false#overview, you should be able to use it from Mac (tested in my Mac).

Let me know how it goes o/ Reopen if it's not working.

**Comment by jungwookim** [comment]
Hi, @pfeodrippe it's still doesn't work for me using m1 macbook. Same result.

**Comment by pfeodrippe** [comment]
> Hi, @pfeodrippe it's still doesn't work for me using m1 macbook. Same result.

Hi @jungwookim, send me a screenshot of what you are seeing, please. You are not even able to install the extension?

**Comment by jungwookim** [comment]
![image](https://user-images.githubusercontent.com/50188177/154875684-e5168c56-9686-4ad2-ba83-63e4e2902177.png)


I hope this will help you

**Comment by pfeodrippe** [comment]
> ![image](https://user-images.githubusercontent.com/50188177/154875684-e5168c56-9686-4ad2-ba83-63e4e2902177.png)
> 
> I hope this will help you

Thanks! I will do it and will let you know o/

**Comment by pfeodrippe** [comment]
Let me know if you are still having the issue
